/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MarketId = IDL.Nat;
export const Bet = IDL.Record({
  'status' : IDL.Text,
  'odds' : IDL.Int,
  'user' : IDL.Principal,
  'isBack' : IDL.Bool,
  'stake' : IDL.Int,
  'selection' : IDL.Nat,
  'marketId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'balance' : IDL.Int,
});
export const Market = IDL.Record({
  'id' : MarketId,
  'status' : IDL.Text,
  'odds' : IDL.Vec(IDL.Vec(IDL.Int)),
  'event' : IDL.Text,
  'sport' : IDL.Text,
  'selections' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMarket' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Vec(IDL.Int))],
      [MarketId],
      [],
    ),
  'getBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMarkets' : IDL.Func([], [IDL.Vec(Market)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeBet' : IDL.Func(
      [MarketId, IDL.Nat, IDL.Int, IDL.Int, IDL.Bool],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBalance' : IDL.Func([IDL.Principal, IDL.Int], [], []),
  'updateMarket' : IDL.Func([MarketId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MarketId = IDL.Nat;
  const Bet = IDL.Record({
    'status' : IDL.Text,
    'odds' : IDL.Int,
    'user' : IDL.Principal,
    'isBack' : IDL.Bool,
    'stake' : IDL.Int,
    'selection' : IDL.Nat,
    'marketId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'balance' : IDL.Int,
  });
  const Market = IDL.Record({
    'id' : MarketId,
    'status' : IDL.Text,
    'odds' : IDL.Vec(IDL.Vec(IDL.Int)),
    'event' : IDL.Text,
    'sport' : IDL.Text,
    'selections' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMarket' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Vec(IDL.Int))],
        [MarketId],
        [],
      ),
    'getBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMarkets' : IDL.Func([], [IDL.Vec(Market)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeBet' : IDL.Func(
        [MarketId, IDL.Nat, IDL.Int, IDL.Int, IDL.Bool],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBalance' : IDL.Func([IDL.Principal, IDL.Int], [], []),
    'updateMarket' : IDL.Func([MarketId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };