/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bet {
  'status' : string,
  'odds' : bigint,
  'user' : Principal,
  'isBack' : boolean,
  'stake' : bigint,
  'selection' : bigint,
  'marketId' : bigint,
}
export interface Market {
  'id' : MarketId,
  'status' : string,
  'odds' : Array<Array<bigint>>,
  'event' : string,
  'sport' : string,
  'selections' : Array<string>,
}
export type MarketId = bigint;
export interface UserProfile { 'username' : string, 'balance' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMarket' : ActorMethod<
    [string, string, Array<string>, Array<Array<bigint>>],
    MarketId
  >,
  'getBets' : ActorMethod<[], Array<Bet>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMarkets' : ActorMethod<[], Array<Market>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeBet' : ActorMethod<
    [MarketId, bigint, bigint, bigint, boolean],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBalance' : ActorMethod<[Principal, bigint], undefined>,
  'updateMarket' : ActorMethod<[MarketId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];